version: "3"
services:
  angular:
    image: jackstones/food-delivery:angular
    # build: Frontend
    ports:
      - "4200:4200"
  express:
    image: jackstones/food-delivery:express
    # build: Backend
    ports:
      - "3000:3000"
    # links:
    #   - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"